config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users
  resources :sessions
  delete '/logout' => 'sessions#destroy', as: :logout

  resources :categories, only: [:show]
  resources :products, only: [:show]

  resources :shopping_carts

  namespace :admin do
    root 'sessions#new'
    resources :sessions
    resources :categories
    resources :products do
      resources :product_images, only: [:index, :create, :destroy, :update]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  validates :title, presence: { message: "名称不能为空"}
  validates :title, uniqueness: { message: "名称不能重复"}

  #因为category模型要用到ancestry，需要配置一下 -> has_ancestry
  #如果删除了一级分类，二级分类也删除掉。orphan_strategy: :destroy
  has_ancestry orphan_strategy: :destroy

  has_many :products, dependent: :destroy #如果这个某个分类被删除，分类下的所有类也要删除,级联删除

  before_validation :correct_ancestry

  def self.groupend_data
    self.roots.order("weight desc").inject([]) do |result,  parent|
      row = []
      row << parent
      row << parent.children.order("weight desc")
      result << row
    end
  end

  private
  def correct_ancestry
    self.ancestry = nil if self.ancestry.blank?
  end

end

app/models/product.rb
class Product < ApplicationRecord



  validates :category_id, presence: { message: "分类不能为空" }
  validates :title, presence: { message: "名称不能为空" }
  validates :status, inclusion: { in: %w[on off], message: "商品状态必须为on|off"}
  validates :amount, numericality: { only_integer: true, message: "库存必须为整数"},
    if: proc { |product| !product.amount.blank? }
  validates :amount, presence: { message: "库存不能为空"}
  validates :msrp, presence: { message: "MSRP不能为空" }
  validates :msrp, numericality: { message: "MSRP必须为数字"},
    if: proc { |product| !product.msrp.blank? }
  validates :price, presence: { message: "价格不能为空" }
  validates :price, numericality: { message: "价格必须为数字"},
    if: proc { |product| !product.price.blank? }
  validates :description, presence: { message: "描述不能为空" }

  belongs_to :category

  has_many :product_images, -> { order(weight: 'desc')}, # -> 指定参数，order排序，根据weight 倒序排列
    dependent: :destroy #dependent 做了级联删除,如果父类被删除了，父类下所属的子类图片也都被删除了。

  has_one :main_product_image, -> {order(weight: 'desc')},
    class_name: :ProductImage

  before_create :set_default_attrs

  scope :onshelf, -> { where(status: Status::On) }


  module Status
    On = 'on'
    Off = 'off'
  end


  private
  def set_default_attrs
    self.uuid = RandomCode.generate_product_uuid
  end

end

app/models/product_image.rb
class ProductImage < ApplicationRecord

  belongs_to :product


  #这几个方法都是paperclip给我们提供的
  #指定生成几张缩略图，small小图，middle中等大小的，big大图
  has_attached_file :image, styles: {
    small: '60^x60',
    middle: '200^x200',
    big: "960x"
  }
  #验证图片的类型
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  #限定图片大小
  validates_attachment_size :image, in: 0..5.megabytes


end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord


  validates :user_uuid, presence: true
  validates :product_id, presence: true
  validates :amount, presence: true

  belongs_to :product

  scope :by_user_uuid, -> (user_uuid) { where(user_uuid: user_uuid) }

end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  attr_accessor :password, :password_confirmation

  validates_presence_of :email, message: "邮箱不能为空"
  validates_format_of :email, message: "邮箱格式不合法",
    with: /\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/,
    if: proc { |user| !user.email.blank? }
  validates :email, uniqueness: { scope: :email, message: "此邮箱已被注册,请更换注册邮箱" }

  validates_presence_of :password, message: "密码不能为空",
    if: :need_validate_password
  validates_presence_of :password_confirmation, message: "密码确认不能为空",
    if: :need_validate_password
  validates_confirmation_of :password, message: "密码不一致",
    if: :need_validate_password
  validates_length_of :password, message: "密码最短为6位", minimum: 6,
    if: :need_validate_password

  def username
    self.email.split('@').first
  end

  private
  def need_validate_password
    self.new_record? ||
      (!self.password.nil? || !self.password_confirmation.nil?)
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ActionController::Base

  layout 'admin/layouts/admin'

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController

  before_action :find_product, only: [:edit, :update, :destroy]

  def index
    @products = Product.page(params[:page] || 1).per_page(params[:per_page] || 10)
      .order("id desc")
  end

  def new
    @product = Product.new
    @root_categories = Category.roots
  end

  def create
    @product = Product.new(params.require(:product).permit!)
    @root_categories = Category.roots

    if @product.save
      flash[:notice] = "创建成功"
      redirect_to admin_products_path
    else
      render action: :new
    end
  end

  def edit
    @root_categories = Category.roots
    render action: :new
  end

  def update
    @product.attributes = params.require(:product).permit!
    @root_categories = Category.roots
    if @product.save
      flash[:notice] = "修改成功"
      redirect_to admin_products_path
    else
      render action: :new
    end
  end

  def destroy
    if @product.destroy
      flash[:notice] = "删除成功"
      redirect_to admin_products_path
    else
      flash[:notice] = "删除失败"
      redirect_to :back
    end
  end

  private
  def find_product
    @product = Product.find(params[:id])
  end

end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::BaseController
  def new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_browser_uuid

  protected
  def fetch_home_data
    @categories = Category.groupend_data
    @shopping_cart_count = ShoppingCart.by_user_uuid(session[:user_uuid]).count
  end

  def set_browser_uuid
    uuid = cookies[:user_uuid]

    unless uuid
      if logged_in?
        uuid = current_user.uuid
      else
        uuid = RandomCode.generate_utoken
      end
    end
    update_browser_uuid uuid
  end

  def update_browser_uuid uuid
    session[:user_uuid] = cookies.permanent['user_uuid'] = uuid
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    fetch_home_data
    
    @category = Category.find(params[:id])
    @products = @category.products.onshelf.page(params[:page] || 1).per_page(params[:per_page] || 12)
      .order("id desc").includes(:main_product_image)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def show
    fetch_home_data
    
    @product = Product.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    #login这个方法是sorcery提供的，不仅仅是可以登录，顺便也
    #帮我们设置好了session,登录的用户信息也已经保存到了浏览器
    if user = login(params[:email], params[:password])
      update_browser_uuid user.uuid
      flash[:notice] = "登录成功"
      redirect_to root_path
    else
      flash[:notice] = "邮箱或者密码不正确"
      redirect_to new_session_path
    end
  end

  def destroy
    logout
    flash[:notice] = "退出成功"
    redirect_to root_path
  end

end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController

  def index
    fetch_home_data
    @shopping_carts = ShoppingCart.by_user_uuid(session[:user_uuid])
    .order("id desc").includes([:product=>[:main_product_image]])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:email, :password, :password_confirmation))
    @user.uuid = session[:user_uuid]
    if @user.save
      flash[:notice] = "注册成功,请登录"
      redirect_to new_session_path
    else
      render action: :new
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @categories = Category.groupend_data
    @products = Product.onshelf.page(params[:page] || 1).per_page(params[:per_page] || 12).order("id desc").includes(:main_product_image)
  end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/layouts/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= admin_root_path %>">管理平台</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= admin_root_path %>">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="<%= admin_categories_path %>">分类</a></li>
        <li><a href="<%= admin_products_path %>">商品</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/admin/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>管理平台 - 智慧商城</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'admin', media: 'all' %>
    <%= yield :stylesheets %>
  </head>

  <body>
    <%= render 'admin/layouts/menu' %>
    <div class="container">
      <% unless flash[:notice].blank? %>
        <div class="alert alert-info"><%= flash[:notice] %></div>
      <% end -%>

      <%= yield %>
    </div>

    <%= javascript_include_tag 'admin' %>
    <%= yield :javascripts %>
  </body>
</html>

app/views/shared/_categories.html.erb
<ul class="list-group">
  <% @categories.each do |group| %>
    <li class="list-group-item"><%= group.first.title %></li>
    <% group.last.each do |sub_category| %>
      <li class="list-group-item"><a href="<%= category_path(sub_category) %>"><%= sub_category.title %></a></li>
    <% end -%>
  <% end -%>
</ul>

app/views/shared/_products.html.erb
<div class="row">
  <% @products.each do |product| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= link_to image_tag(product.main_product_image.image.url(:middle), alt: product.title), product_path(product) %>
        <div class="caption">
          <h4><%= link_to product.title, product_path(product), class: 'title' %></h4>
          <p><strong>¥<%= product.price %></strong> <span class="msrp">¥<%= product.msrp %></span></p>
          <p><a href="#" class="btn btn-danger btn-sm" role="button">加入购物车</a></p>
        </div>
      </div>
    </div>
  <% end -%>
</div>

<%= will_paginate @products %>